### ISSUE TITLE
User changes aren't reflected on a wall until refresh

### ISSUE THREAD

**Issue by niventc** [niventc/wally#1]
If a user changes their name or colour after joining a wall, it won't be updated until  a page refresh

**Comment by sleol** [comment]
This also applies to the first line drawn using the pencil tool. The same issue occurs after a period of inactivity as well as first joining.

**Comment by niventc** [comment]
On creating a wall not showing lines until refresh should be fixed since (https://github.com/niventc/wally/commit/a25f4c2bd9f6fa34ecec47726d43d69f7481423b).

User changes should be updated since https://github.com/niventc/wally/commit/9d316778e67b4990b33264e0e7c8d5fd9264037b and https://github.com/niventc/wally/commit/9c9f85fd0b48e41523b4ef139e781a5f90562ee4.

Will look into the period of inactivity one, suspect it is related to https://github.com/niventc/wally/issues/3.
